# Generated by Django 5.0.4 on 2024-04-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officer_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='officer_registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(max_length=14)),
                ('phone_contact', models.IntegerField()),
                ('officer_address', models.CharField(max_length=250)),
                ('officer_cuurent_rank', models.CharField(max_length=24)),
                ('officer_current_station', models.CharField(max_length=24)),
                ('officer_staff_ID', models.CharField(max_length=12)),
                ('officer_qualification', models.CharField(max_length=9)),
                ('officer_dateofbirth', models.DateField()),
                ('officer_place_of_operations', models.CharField(max_length=24)),
                ('officer_department_of_operations', models.CharField(max_length=16)),
                ('officer_image', models.ImageField(upload_to='')),
                ('password_two', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='portalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('details', models.CharField(default=0, max_length=250)),
            ],
        ),
    ]
