# Generated by Django 5.0.4 on 2024-04-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer_registrations',
            old_name='officer_dateofbirth',
            new_name='officer_date_of_birth',
        ),
    ]
