# Generated by Django 5.0.4 on 2024-04-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0002_rename_officer_dateofbirth_officer_registrations_officer_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='portalUsers',
        ),
    ]
