# Generated by Django 5.0.4 on 2024-04-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0003_delete_portalusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer_registrations',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
