# Generated by Django 5.0.4 on 2024-04-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0004_alter_officer_registrations_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officer_registrations',
            old_name='password_two',
            new_name='password',
        ),
    ]
