# Generated by Django 5.0.4 on 2024-04-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0005_rename_password_two_officer_registrations_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_officer_registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_contact', models.IntegerField()),
                ('officer_address', models.CharField(max_length=250)),
                ('officer_cuurent_rank', models.CharField(max_length=250)),
                ('officer_current_station', models.CharField(max_length=250)),
                ('officer_staff_ID', models.CharField(max_length=12)),
                ('officer_qualification', models.CharField(max_length=250)),
                ('officer_date_of_birth', models.DateField()),
                ('officer_place_of_operations', models.CharField(max_length=250)),
                ('officer_department_of_operations', models.CharField(max_length=24)),
                ('officer_image', models.ImageField(upload_to='')),
                ('password', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='officer_registrations',
        ),
    ]
