# Generated by Django 5.0.4 on 2024-04-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0008_rename_officer_cuurent_rank_new_officer_registrations_officer_current_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer_login',
            name='username',
        ),
        migrations.AddField(
            model_name='officer_login',
            name='officer_staff_ID',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_officer_registrations',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
