# Generated by Django 5.0.4 on 2024-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0010_alter_new_officer_registrations_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_officer_registrations',
            name='phone_contact',
            field=models.IntegerField(unique=True),
        ),
    ]
