# Generated by Django 5.0.4 on 2024-05-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0012_alter_new_officer_registrations_officer_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_officer_registrations',
            old_name='officer_image',
            new_name='officer_profile_image',
        ),
    ]
