# Generated by Django 5.0.4 on 2024-05-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0013_rename_officer_image_new_officer_registrations_officer_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_officer_registrations',
            old_name='officer_department_of_operations',
            new_name='officer_operations_department',
        ),
        migrations.RenameField(
            model_name='new_officer_registrations',
            old_name='officer_place_of_operations',
            new_name='officer_Operations_region',
        ),
        migrations.AlterField(
            model_name='new_officer_registrations',
            name='officer_qualification',
            field=models.CharField(choices=[('WS', 'WASSCE'), ('DG', 'DEGREE'), ('MS', 'MASTERS'), ('PH', 'PHD')], max_length=2),
        ),
    ]
