# Generated by Django 5.0.4 on 2024-05-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0014_rename_officer_department_of_operations_new_officer_registrations_officer_operations_department_and_'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_officer_registrations',
            name='officer_qualification',
            field=models.CharField(choices=[('WS', 'WASSCE'), ('DG', 'DEGREE'), ('MS', 'MASTERS'), ('PH', 'PHD')], max_length=250),
        ),
    ]
