# Generated by Django 4.2.8 on 2024-05-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0016_newofficerregistration_officerlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newofficerregistration',
            name='officer_current_rank',
            field=models.CharField(choices=[('Constable', 'Constable'), ('Lance Corporal', 'Lance Corporal'), ('Corporal', 'Corporal'), ('Sergeant', 'Sergeant'), ('District Sergeant Major', 'District Sergeant Major'), ('Inspector', 'Inspector'), ('Regional Sergeant Major', 'Regional Sergeant Major'), ('Chief Inspector', 'Chief Inspector'), ('Assistant Superintendent of Police', 'Assistant Superintendent of Police'), ('Deputy Superintendent of Police', 'Deputy Superintendent of Police'), ('Superintendent of Police', 'Superintendent of Police'), ('Chief Superintendent', 'Chief Superintendent'), ('Assistant Commissioner of Police', 'Assistant Commissioner of Police'), ('Deputy Commissioner of Police', 'Deputy Commissioner of Police'), ('Commissioner of Police', 'Commissioner of Police'), ('Inspector General of Police', 'Inspector General of Police')], max_length=250),
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='officer_operations_department',
            field=models.CharField(choices=[('CID', 'Criminal Investigation Department [CID]'), ('MTTD', 'Motor Traffic and Transport Directorate [MTTD]'), ('DOVVSU', 'Domestic Violence and Victim Support Unit [DOVVSU]'), ('The Police College', 'The Police College'), ('Other Training Institutions', 'Other Training Institutions'), ('W&H', 'Works & Housing Department'), ('PRD', 'Public Relations Department'), ('MH', 'Medical – Hospital'), ('Marine Ports & Railways', 'Marine Ports & Railways'), ('Community Policing', 'Community Policing')], max_length=250),
        ),
        migrations.AlterField(
            model_name='officerlogin',
            name='officer_staff_ID',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
