# Generated by Django 4.2.8 on 2024-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0017_alter_newofficerregistration_officer_current_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newofficerregistration',
            name='officer_qualification',
            field=models.CharField(choices=[('WS', 'WASSCE'), ('DG', 'DEGREE'), ('MS', 'MASTERS'), ('PH', 'PHD')], max_length=250),
        ),
    ]
