# Generated by Django 5.0.4 on 2024-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0018_alter_newofficerregistration_officer_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='newofficerregistration',
            name='Create_username',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='newofficerregistration',
            name='officer_gender',
            field=models.CharField(choices=[('M', 'Constable'), ('F', 'Lance Corporal')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
