# Generated by Django 5.0.4 on 2024-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0020_alter_newofficerregistration_create_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newofficerregistration',
            name='Create_username',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='officer_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=250),
        ),
    ]
