# Generated by Django 5.0.4 on 2024-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0023_alter_newofficerregistration_create_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newofficerregistration',
            name='Create_username',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
