# Generated by Django 5.0.4 on 2024-05-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0026_alter_newofficerregistration_create_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newofficerregistration',
            old_name='Create_username',
            new_name='username',
        ),
    ]
