# Generated by Django 5.0.4 on 2024-05-05 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0027_rename_create_username_newofficerregistration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerlogin',
            name='email',
            field=models.EmailField(default='to provide', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='officerlogin',
            name='phone_contact',
            field=models.IntegerField(default=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officerlogin',
            name='username',
            field=models.CharField(default=50, max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, unique=True),
        ),
    ]
