# Generated by Django 5.0.4 on 2024-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0028_officerlogin_email_officerlogin_phone_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newofficerregistration',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
