# Generated by Django 5.0.4 on 2024-05-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0029_alter_newofficerregistration_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerlogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='officer_staff_ID',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='phone_contact',
        ),
        migrations.AlterField(
            model_name='newofficerregistration',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
