# Generated by Django 5.0.4 on 2024-05-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0030_remove_officerlogin_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officerlogin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='officerlogin',
            name='username',
        ),
        migrations.AddField(
            model_name='officerlogin',
            name='user',
            field=models.OneToOneField(default=250, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
