# Generated by Django 5.0.4 on 2024-05-06 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices', '0032_remove_officerlogin_user_officerlogin_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfficerLogin',
        ),
    ]
